# Generated by Django 4.0.4 on 2022-05-08 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setName', models.CharField(max_length=120, verbose_name='Set Name')),
                ('yearReleased', models.DateField(verbose_name='Released')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, verbose_name='Item Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Item Image')),
                ('rrp_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Recommended Retail Price')),
                ('init_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial Price')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Price')),
                ('on_sale', models.BooleanField(verbose_name='On Sale')),
                ('size_index', models.IntegerField(verbose_name='Size Index')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('setName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flaashCollectables.pokemonset')),
            ],
        ),
    ]
