# Generated by Django 4.0.4 on 2022-05-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setName', models.CharField(max_length=120, verbose_name='Set Name')),
                ('yearReleased', models.DateField(verbose_name='Released')),
            ],
        ),
        migrations.CreateModel(
            name='SellToUsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('emailAddress', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('addressLine1', models.CharField(max_length=200, verbose_name='Address Line')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('postCode', models.CharField(max_length=50, verbose_name='Post Code')),
                ('cucCards', models.IntegerField(verbose_name='Common Uncommon Cards')),
                ('rCards', models.IntegerField(verbose_name='Rare Cards')),
                ('rholoCards', models.IntegerField(verbose_name='Reverse Holo Cards')),
                ('holoCards', models.IntegerField(verbose_name='Holo Cards')),
                ('specialCards', models.IntegerField(verbose_name='Special Cards')),
                ('vCards', models.IntegerField(verbose_name='V Cards')),
                ('energyCards', models.IntegerField(verbose_name='Energy Cards')),
                ('trainerCards', models.IntegerField(verbose_name='Trainer Cards')),
                ('totalCards', models.IntegerField(verbose_name='Total Cards')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200, verbose_name='Item Name')),
                ('description', models.TextField(blank=True, verbose_name='Item Description')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Item Image')),
                ('rrp_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Recommended Retail Price')),
                ('init_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial Price')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale Price')),
                ('on_sale', models.BooleanField(verbose_name='On Sale')),
                ('size_index', models.IntegerField(verbose_name='Size Index')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('setName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flaashCollectables.pokemonset')),
            ],
        ),
    ]
